#!/usr/bin/env python3.4


import alimaster

from tkinter import *
from tkinter.ttk import *

from argparse import ArgumentParser

import logging

def main():

  parser = ArgumentParser()
  parser.add_argument("-c", "--conf", metavar="FILE", help="Load configuration")
  parser.add_argument("-v", "--verbose", dest='verbose', action='store_true', help="Print helpful information")
  args = parser.parse_args()

  log = logging.getLogger('lout')
  log.setLevel(logging.DEBUG if args.verbose else logging.INFO)

  log.info("Alimaster starting with config file '%s'" % (args.conf))

  app  = alimaster.Application(opts = args, gui_thread=False)
  # main = alimaster.MainWindow()

  app.handle_signals()

  #app._build_interface()
  #app.root.mainloop()
  app.run()

  # app.run_in_thread()
  # app.gui_thread.join()
  print ("GUI has finished")

  # root.withdraw()
  # root.mainloop()

if __name__ == '__main__':
  main()
