#!/usr/bin/env python3
#
# alimaster-root-selector
#
"""
A launcher script for the root_selector subpackage of alimaster
"""

import sys

from alimaster.root_selector import main

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
