#!/usr/bin/env python3.4
#
# alimaster
#
"""
A script to run the 'main' routine of the alimaster package
"""

import sys
from alimaster.__main__ import main

if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
